// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PayService.Model;
using PayService.Model.Data.Embed;
using System;

namespace PayService.Model.Migrations
{
    [DbContext(typeof(PayServiceDbContext))]
    partial class PayServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PayService.Model.Data.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountNumber");

                    b.Property<int>("Amount");

                    b.Property<string>("BankNumber");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("IndividualNumber");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PurposeOfPayment");

                    b.Property<int>("Vat");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("PayService.Model.Data.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("CardNumber");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("MonthExpired");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
